baseURL               = "https://xorange.cafe/"
languageCode          = "zh-CN"
title                 = "橙子果园"
theme                 = "WebStack"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"					# 站点静态文件保存目录


[params]
    author        = "Dreamin"
    description   = "Webstack-Hugo 网址导航 | Hugo 主题 BY Bio IT 爱好者"
    upload        = "mailto:12185744@qq.com"  # 左侧导航栏的"网站提交"
    about         = "https://shumlab.com/cookbook/webstack-hugo"	# 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"  
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "欢迎来到小瓜田"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = true					# 默认站点为深色(夜间)模式
    yiyan         = true                         		# 默认启用一言服务

[params.seo]    
    baiduhmid       = 'efccc04cb44fc49faddac5876180b369'	# 百度统计 hm.src 的 ID
    baiduSiteVer    = 'codeva-cCAOSG8MBO'			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "https://cdn.staticaly.com/gh/Dreamin121/picgohub@master/orange.png"
    searchImageL      = "https://cdn.staticaly.com/gh/Dreamin121/picgohub@master/imgs/01598e5db26aa4a801209e1f4c7784.gif"		# 搜索部分浅色背景图
    searchImageD      = "https://cdn.staticaly.com/gh/Dreamin121/picgohub@master/imgs/01598e5db26aa4a801209e1f4c7784.gif"		# 搜索部分深色背景图
    logoExpandLight   = "https://cdn.staticaly.com/gh/Dreamin121/picgohub@master/xmelon.webp"
    logoExpandDark    = "https://cdn.staticaly.com/gh/Dreamin121/picgohub@master/xmelon.webp"
    logoCollapseLight = "https://cdn.staticaly.com/gh/Dreamin121/picgohub@master/xmelon.webp"
    logoCollapseDark  = "https://cdn.staticaly.com/gh/Dreamin121/picgohub@master/xmelon.webp"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '&copy; 2022 - {year} · Dreamin<br/>'
